name: AutoUpdate

on:
  schedule:
    - cron:  '0 12 * * 5'

jobs:
  AutoUpdate:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@477b21f02be01bcb8030d50f37cfec92bfa615b6
        with:
          ruby-version: 2.6
      - name: Run update
        run: |
          cd _data
          ruby update.rb
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
            token: ${{ secrets.GITHUB_TOKEN }}
            commit-message: [GHA] Update data
            title: [GHA] Update data
            body: |
              - This is an automated pull request.
            branch: update-dependencies